#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAB4655A126D292E4 (coreteam@netfilter.org)
#
Name     : compat-iptables-soname0.1.0
Version  : 1.8.2
Release  : 3
URL      : https://www.netfilter.org/projects/iptables/files/iptables-1.8.2.tar.bz2
Source0  : https://www.netfilter.org/projects/iptables/files/iptables-1.8.2.tar.bz2
Source1 : https://www.netfilter.org/projects/iptables/files/iptables-1.8.2.tar.bz2.sig
Summary  : Shared Xtables code for extensions and iproute2
Group    : Development/Tools
License  : GPL-2.0
Requires: compat-iptables-soname0.1.0-bin = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-data = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-lib = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-license = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnetfilter_conntrack)
BuildRequires : pkgconfig(libnfnetlink)
BuildRequires : pkgconfig(libnftnl)
Patch1: cve-2012-2663.patch
Patch2: cve-2019-11360.patch

%description
No detailed description available

%package bin
Summary: bin components for the compat-iptables-soname0.1.0 package.
Group: Binaries
Requires: compat-iptables-soname0.1.0-data = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-license = %{version}-%{release}

%description bin
bin components for the compat-iptables-soname0.1.0 package.


%package data
Summary: data components for the compat-iptables-soname0.1.0 package.
Group: Data

%description data
data components for the compat-iptables-soname0.1.0 package.


%package dev
Summary: dev components for the compat-iptables-soname0.1.0 package.
Group: Development
Requires: compat-iptables-soname0.1.0-lib = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-bin = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-data = %{version}-%{release}
Provides: compat-iptables-soname0.1.0-devel = %{version}-%{release}
Requires: compat-iptables-soname0.1.0 = %{version}-%{release}

%description dev
dev components for the compat-iptables-soname0.1.0 package.


%package lib
Summary: lib components for the compat-iptables-soname0.1.0 package.
Group: Libraries
Requires: compat-iptables-soname0.1.0-data = %{version}-%{release}
Requires: compat-iptables-soname0.1.0-license = %{version}-%{release}

%description lib
lib components for the compat-iptables-soname0.1.0 package.


%package license
Summary: license components for the compat-iptables-soname0.1.0 package.
Group: Default

%description license
license components for the compat-iptables-soname0.1.0 package.


%package man
Summary: man components for the compat-iptables-soname0.1.0 package.
Group: Default

%description man
man components for the compat-iptables-soname0.1.0 package.


%prep
%setup -q -n iptables-1.8.2
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1563214572
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --enable-devel --enable-ipv6
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1563214572
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-iptables-soname0.1.0
cp COPYING %{buildroot}/usr/share/package-licenses/compat-iptables-soname0.1.0/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/arptables
%exclude /usr/bin/arptables-nft
%exclude /usr/bin/arptables-nft-restore
%exclude /usr/bin/arptables-nft-save
%exclude /usr/bin/arptables-restore
%exclude /usr/bin/arptables-save
%exclude /usr/bin/ebtables
%exclude /usr/bin/ebtables-nft
%exclude /usr/bin/ebtables-nft-restore
%exclude /usr/bin/ebtables-nft-save
%exclude /usr/bin/ebtables-restore
%exclude /usr/bin/ebtables-save
%exclude /usr/bin/ip6tables
%exclude /usr/bin/ip6tables-legacy
%exclude /usr/bin/ip6tables-legacy-restore
%exclude /usr/bin/ip6tables-legacy-save
%exclude /usr/bin/ip6tables-nft
%exclude /usr/bin/ip6tables-nft-restore
%exclude /usr/bin/ip6tables-nft-save
%exclude /usr/bin/ip6tables-restore
%exclude /usr/bin/ip6tables-restore-translate
%exclude /usr/bin/ip6tables-save
%exclude /usr/bin/ip6tables-translate
%exclude /usr/bin/iptables
%exclude /usr/bin/iptables-legacy
%exclude /usr/bin/iptables-legacy-restore
%exclude /usr/bin/iptables-legacy-save
%exclude /usr/bin/iptables-nft
%exclude /usr/bin/iptables-nft-restore
%exclude /usr/bin/iptables-nft-save
%exclude /usr/bin/iptables-restore
%exclude /usr/bin/iptables-restore-translate
%exclude /usr/bin/iptables-save
%exclude /usr/bin/iptables-translate
%exclude /usr/bin/iptables-xml
%exclude /usr/bin/nfnl_osf
%exclude /usr/bin/xtables-legacy-multi
%exclude /usr/bin/xtables-monitor
%exclude /usr/bin/xtables-nft-multi

%files data
%defattr(-,root,root,-)
%exclude /usr/share/xtables/pf.os

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/libiptc/ipt_kernel_headers.h
%exclude /usr/include/libiptc/libip6tc.h
%exclude /usr/include/libiptc/libiptc.h
%exclude /usr/include/libiptc/libxtc.h
%exclude /usr/include/libiptc/xtcshared.h
%exclude /usr/include/xtables-version.h
%exclude /usr/include/xtables.h
%exclude /usr/lib64/libip4tc.so
%exclude /usr/lib64/libip6tc.so
%exclude /usr/lib64/libiptc.so
%exclude /usr/lib64/libxtables.so
%exclude /usr/lib64/pkgconfig/libip4tc.pc
%exclude /usr/lib64/pkgconfig/libip6tc.pc
%exclude /usr/lib64/pkgconfig/libiptc.pc
%exclude /usr/lib64/pkgconfig/xtables.pc

%files lib
%defattr(-,root,root,-)
%exclude /usr/lib64/libiptc.so.0.0.0
%exclude /usr/lib64/libxtables.so.12.2.0
%exclude /usr/lib64/xtables/libarpt_mangle.so
%exclude /usr/lib64/xtables/libebt_802_3.so
%exclude /usr/lib64/xtables/libebt_arp.so
%exclude /usr/lib64/xtables/libebt_arpreply.so
%exclude /usr/lib64/xtables/libebt_dnat.so
%exclude /usr/lib64/xtables/libebt_ip.so
%exclude /usr/lib64/xtables/libebt_ip6.so
%exclude /usr/lib64/xtables/libebt_log.so
%exclude /usr/lib64/xtables/libebt_mark.so
%exclude /usr/lib64/xtables/libebt_mark_m.so
%exclude /usr/lib64/xtables/libebt_nflog.so
%exclude /usr/lib64/xtables/libebt_pkttype.so
%exclude /usr/lib64/xtables/libebt_redirect.so
%exclude /usr/lib64/xtables/libebt_snat.so
%exclude /usr/lib64/xtables/libebt_stp.so
%exclude /usr/lib64/xtables/libebt_vlan.so
%exclude /usr/lib64/xtables/libip6t_DNAT.so
%exclude /usr/lib64/xtables/libip6t_DNPT.so
%exclude /usr/lib64/xtables/libip6t_HL.so
%exclude /usr/lib64/xtables/libip6t_LOG.so
%exclude /usr/lib64/xtables/libip6t_MASQUERADE.so
%exclude /usr/lib64/xtables/libip6t_NETMAP.so
%exclude /usr/lib64/xtables/libip6t_REDIRECT.so
%exclude /usr/lib64/xtables/libip6t_REJECT.so
%exclude /usr/lib64/xtables/libip6t_SNAT.so
%exclude /usr/lib64/xtables/libip6t_SNPT.so
%exclude /usr/lib64/xtables/libip6t_ah.so
%exclude /usr/lib64/xtables/libip6t_dst.so
%exclude /usr/lib64/xtables/libip6t_eui64.so
%exclude /usr/lib64/xtables/libip6t_frag.so
%exclude /usr/lib64/xtables/libip6t_hbh.so
%exclude /usr/lib64/xtables/libip6t_hl.so
%exclude /usr/lib64/xtables/libip6t_icmp6.so
%exclude /usr/lib64/xtables/libip6t_ipv6header.so
%exclude /usr/lib64/xtables/libip6t_mh.so
%exclude /usr/lib64/xtables/libip6t_rt.so
%exclude /usr/lib64/xtables/libip6t_srh.so
%exclude /usr/lib64/xtables/libipt_CLUSTERIP.so
%exclude /usr/lib64/xtables/libipt_DNAT.so
%exclude /usr/lib64/xtables/libipt_ECN.so
%exclude /usr/lib64/xtables/libipt_LOG.so
%exclude /usr/lib64/xtables/libipt_MASQUERADE.so
%exclude /usr/lib64/xtables/libipt_NETMAP.so
%exclude /usr/lib64/xtables/libipt_REDIRECT.so
%exclude /usr/lib64/xtables/libipt_REJECT.so
%exclude /usr/lib64/xtables/libipt_SNAT.so
%exclude /usr/lib64/xtables/libipt_TTL.so
%exclude /usr/lib64/xtables/libipt_ULOG.so
%exclude /usr/lib64/xtables/libipt_ah.so
%exclude /usr/lib64/xtables/libipt_icmp.so
%exclude /usr/lib64/xtables/libipt_realm.so
%exclude /usr/lib64/xtables/libipt_ttl.so
%exclude /usr/lib64/xtables/libxt_AUDIT.so
%exclude /usr/lib64/xtables/libxt_CHECKSUM.so
%exclude /usr/lib64/xtables/libxt_CLASSIFY.so
%exclude /usr/lib64/xtables/libxt_CONNMARK.so
%exclude /usr/lib64/xtables/libxt_CONNSECMARK.so
%exclude /usr/lib64/xtables/libxt_CT.so
%exclude /usr/lib64/xtables/libxt_DSCP.so
%exclude /usr/lib64/xtables/libxt_HMARK.so
%exclude /usr/lib64/xtables/libxt_IDLETIMER.so
%exclude /usr/lib64/xtables/libxt_LED.so
%exclude /usr/lib64/xtables/libxt_MARK.so
%exclude /usr/lib64/xtables/libxt_NFLOG.so
%exclude /usr/lib64/xtables/libxt_NFQUEUE.so
%exclude /usr/lib64/xtables/libxt_NOTRACK.so
%exclude /usr/lib64/xtables/libxt_RATEEST.so
%exclude /usr/lib64/xtables/libxt_SECMARK.so
%exclude /usr/lib64/xtables/libxt_SET.so
%exclude /usr/lib64/xtables/libxt_SYNPROXY.so
%exclude /usr/lib64/xtables/libxt_TCPMSS.so
%exclude /usr/lib64/xtables/libxt_TCPOPTSTRIP.so
%exclude /usr/lib64/xtables/libxt_TEE.so
%exclude /usr/lib64/xtables/libxt_TOS.so
%exclude /usr/lib64/xtables/libxt_TPROXY.so
%exclude /usr/lib64/xtables/libxt_TRACE.so
%exclude /usr/lib64/xtables/libxt_addrtype.so
%exclude /usr/lib64/xtables/libxt_bpf.so
%exclude /usr/lib64/xtables/libxt_cgroup.so
%exclude /usr/lib64/xtables/libxt_cluster.so
%exclude /usr/lib64/xtables/libxt_comment.so
%exclude /usr/lib64/xtables/libxt_connbytes.so
%exclude /usr/lib64/xtables/libxt_connlabel.so
%exclude /usr/lib64/xtables/libxt_connlimit.so
%exclude /usr/lib64/xtables/libxt_connmark.so
%exclude /usr/lib64/xtables/libxt_conntrack.so
%exclude /usr/lib64/xtables/libxt_cpu.so
%exclude /usr/lib64/xtables/libxt_dccp.so
%exclude /usr/lib64/xtables/libxt_devgroup.so
%exclude /usr/lib64/xtables/libxt_dscp.so
%exclude /usr/lib64/xtables/libxt_ecn.so
%exclude /usr/lib64/xtables/libxt_esp.so
%exclude /usr/lib64/xtables/libxt_hashlimit.so
%exclude /usr/lib64/xtables/libxt_helper.so
%exclude /usr/lib64/xtables/libxt_ipcomp.so
%exclude /usr/lib64/xtables/libxt_iprange.so
%exclude /usr/lib64/xtables/libxt_ipvs.so
%exclude /usr/lib64/xtables/libxt_length.so
%exclude /usr/lib64/xtables/libxt_limit.so
%exclude /usr/lib64/xtables/libxt_mac.so
%exclude /usr/lib64/xtables/libxt_mark.so
%exclude /usr/lib64/xtables/libxt_multiport.so
%exclude /usr/lib64/xtables/libxt_nfacct.so
%exclude /usr/lib64/xtables/libxt_osf.so
%exclude /usr/lib64/xtables/libxt_owner.so
%exclude /usr/lib64/xtables/libxt_physdev.so
%exclude /usr/lib64/xtables/libxt_pkttype.so
%exclude /usr/lib64/xtables/libxt_policy.so
%exclude /usr/lib64/xtables/libxt_quota.so
%exclude /usr/lib64/xtables/libxt_rateest.so
%exclude /usr/lib64/xtables/libxt_recent.so
%exclude /usr/lib64/xtables/libxt_rpfilter.so
%exclude /usr/lib64/xtables/libxt_sctp.so
%exclude /usr/lib64/xtables/libxt_set.so
%exclude /usr/lib64/xtables/libxt_socket.so
%exclude /usr/lib64/xtables/libxt_standard.so
%exclude /usr/lib64/xtables/libxt_state.so
%exclude /usr/lib64/xtables/libxt_statistic.so
%exclude /usr/lib64/xtables/libxt_string.so
%exclude /usr/lib64/xtables/libxt_tcp.so
%exclude /usr/lib64/xtables/libxt_tcpmss.so
%exclude /usr/lib64/xtables/libxt_time.so
%exclude /usr/lib64/xtables/libxt_tos.so
%exclude /usr/lib64/xtables/libxt_u32.so
%exclude /usr/lib64/xtables/libxt_udp.so
/usr/lib64/libip4tc.so.0
/usr/lib64/libip4tc.so.0.1.0
/usr/lib64/libip6tc.so.0
/usr/lib64/libip6tc.so.0.1.0
/usr/lib64/libiptc.so.0
/usr/lib64/libxtables.so.12

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-iptables-soname0.1.0/COPYING

%files man
%defattr(0644,root,root,0755)
%exclude /usr/share/man/man1/iptables-xml.1
%exclude /usr/share/man/man8/ip6tables-restore.8
%exclude /usr/share/man/man8/ip6tables-save.8
%exclude /usr/share/man/man8/ip6tables.8
%exclude /usr/share/man/man8/iptables-extensions.8
%exclude /usr/share/man/man8/iptables-restore.8
%exclude /usr/share/man/man8/iptables-save.8
%exclude /usr/share/man/man8/iptables.8
%exclude /usr/share/man/man8/nfnl_osf.8
%exclude /usr/share/man/man8/xtables-legacy.8
%exclude /usr/share/man/man8/xtables-monitor.8
%exclude /usr/share/man/man8/xtables-nft.8
%exclude /usr/share/man/man8/xtables-translate.8
